version: 2
updates:
  - package-ecosystem: npm
    directory: /
    groups:
      vscode-languageserver-node:
        patterns:
          - vscode-languageclient
          - vscode-languageserver
      trpc:
        patterns:
          - "@trpc/client"
          - "@trpc/server"
      react:
        patterns:
          - react
          - react-dom
      nextra:
        patterns:
          - nextra
          - nextra-theme-docs
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    ignore:
      - dependency-name: "@types/vscode"
    schedule:
      interval: weekly

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
