packages:
  - 'apps/*'
  - 'apps/extension/browser/*'
  - 'apps/extension/desktop/*'
  - 'packages/*'

catalog:
  '@sveltejs/vite-plugin-svelte': ^5.1.1
  '@tsconfig/svelte': ^5.0.4
  '@types/vscode-webview': ^1.57.5
  svelte: ^5.39.10
  vite: ^6.3.6
  vscode-languageclient: ^9.0.1
  vscode-languageserver: ^9.0.1

onlyBuiltDependencies:
  - '@playwright/browser-chromium'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
  - sharp
