packages:
  - 'apps/*'
  - 'apps/extension/browser/*'
  - 'apps/extension/desktop/*'
  - 'packages/*'

catalog:
  '@sveltejs/vite-plugin-svelte': ^5.1.1
  '@tsconfig/svelte': ^5.0.4
  '@types/vscode-webview': ^1.57.5
  svelte: ^5.34.1
  vscode-languageclient: ^9.0.1
  vscode-languageserver: ^9.0.1
