packages:
  - 'apps/*'
  - 'apps/extension/browser/*'
  - 'apps/extension/desktop/*'
  - 'packages/*'

catalog:
  '@sveltejs/vite-plugin-svelte': ^6.2.1
  '@tsconfig/svelte': ^5.0.6
  '@types/vscode-webview': ^1.57.5
  svelte: ^5.48.0
  vite: ^7.2.7
  vscode-languageclient: ^9.0.1
  vscode-languageserver: ^9.0.1

onlyBuiltDependencies:
  - '@playwright/browser-chromium'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
  - sharp
