import { CompletionItem, CompletionItemKind } from "vscode-languageserver-types"

export const statichudKeyBitValues = [
	"auto_wide_tocontents",
	"auto_tall_tocontents",
	"visible",
	"enabled",
	"paintbackground",
	"paintborder",
	"use_proportional_insets",
	"proportionaltoparent",
]

const autoResizeValues: CompletionItem[] = [
	{ label: "AUTORESIZE_NO", kind: CompletionItemKind.Enum, detail: "0" },
	{ label: "AUTORESIZE_RIGHT", kind: CompletionItemKind.Enum, detail: "1" },
	{ label: "AUTORESIZE_DOWN", kind: CompletionItemKind.Enum, detail: "2" },
	{ label: "AUTORESIZE_DOWNANDRIGHT", kind: CompletionItemKind.Enum, detail: "3" }
]

const pinValues: CompletionItem[] = [
	{ label: "PIN_TOPLEFT", kind: CompletionItemKind.Enum, detail: "0" },
	{ label: "PIN_TOPRIGHT", kind: CompletionItemKind.Enum, detail: "1" },
	{ label: "PIN_BOTTOMLEFT", kind: CompletionItemKind.Enum, detail: "2" },
	{ label: "PIN_BOTTOMRIGHT", kind: CompletionItemKind.Enum, detail: "3" },
	{ label: "PIN_CENTER_TOP", kind: CompletionItemKind.Enum, detail: "4" },
	{ label: "PIN_CENTER_RIGHT", kind: CompletionItemKind.Enum, detail: "5" },
	{ label: "PIN_CENTER_BOTTOM", kind: CompletionItemKind.Enum, detail: "6" },
	{ label: "PIN_CENTER_LEFT", kind: CompletionItemKind.Enum, detail: "7" },
	{ label: "PIN_LAST", kind: CompletionItemKind.Enum, detail: "8" },
]

export const statichudKeyValues: Record<string, CompletionItem[]> = {
	"controlname": [
		{ label: "AnalogBar", kind: CompletionItemKind.Class },
		{ label: "AnimatingImagePanel", kind: CompletionItemKind.Class },
		{ label: "BuildModeDialog", kind: CompletionItemKind.Class },
		{ label: "Button", kind: CompletionItemKind.Class },
		{ label: "CAchievementsDialog", kind: CompletionItemKind.Class },
		{ label: "CArmoryPanel", kind: CompletionItemKind.Class },
		{ label: "CAutoFittingLabel", kind: CompletionItemKind.Class },
		{ label: "CAvatarImagePanel", kind: CompletionItemKind.Class },
		{ label: "CBackpackPanel", kind: CompletionItemKind.Class },
		{ label: "CBaseModelPanel", kind: CompletionItemKind.Class },
		{ label: "CBasicTraining_ClassDetailsPanel", kind: CompletionItemKind.Class },
		{ label: "CBasicTraining_ClassSelectionPanel", kind: CompletionItemKind.Class },
		{ label: "CBitmapImagePanel", kind: CompletionItemKind.Class },
		{ label: "CBitmapPanel", kind: CompletionItemKind.Class },
		{ label: "CBuildingHealthBar", kind: CompletionItemKind.Class },
		{ label: "CBuildingStatusAlertTray", kind: CompletionItemKind.Class },
		{ label: "CCasualCriteriaPanel", kind: CompletionItemKind.Class },
		{ label: "CClassLoadoutPanel", kind: CompletionItemKind.Class },
		{ label: "CClassMenu", kind: CompletionItemKind.Class },
		{ label: "CCommentaryExplanationDialog", kind: CompletionItemKind.Class },
		{ label: "CCommentaryItemPanel", kind: CompletionItemKind.Class },
		{ label: "CCompetitiveAccessInfoPanel", kind: CompletionItemKind.Class },
		{ label: "CControllerMap", kind: CompletionItemKind.Class },
		{ label: "CControlPointCountdown", kind: CompletionItemKind.Class },
		{ label: "CCreditDisplayPanel", kind: CompletionItemKind.Class },
		{ label: "CCreditSpendPanel", kind: CompletionItemKind.Class },
		{ label: "CCurrencyStatusPanel", kind: CompletionItemKind.Class },
		{ label: "CCustomTextureImagePanel", kind: CompletionItemKind.Class },
		{ label: "CCvarSlider", kind: CompletionItemKind.Class },
		{ label: "CCvarToggleCheckButton", kind: CompletionItemKind.Class },
		{ label: "CCyclingAdContainerPanel", kind: CompletionItemKind.Class },
		{ label: "CDashboardPartyMember", kind: CompletionItemKind.Class },
		{ label: "CDrawingPanel", kind: CompletionItemKind.Class },
		{ label: "CEconItemDetailsRichText", kind: CompletionItemKind.Class },
		{ label: "CEmbeddedItemModelPanel", kind: CompletionItemKind.Class },
		{ label: "CEngyDestroyMenuItem", kind: CompletionItemKind.Class },
		{ label: "CEventPlayListEntry", kind: CompletionItemKind.Class },
		{ label: "CExButton", kind: CompletionItemKind.Class },
		{ label: "CExCheckButton", kind: CompletionItemKind.Class },
		{ label: "CExImageButton", kind: CompletionItemKind.Class },
		{ label: "CExLabel", kind: CompletionItemKind.Class },
		{ label: "CExpandablePanel", kind: CompletionItemKind.Class },
		{ label: "CExplanationPopup", kind: CompletionItemKind.Class },
		{ label: "CExRichText", kind: CompletionItemKind.Class },
		{ label: "CExScrollingEditablePanel", kind: CompletionItemKind.Class },
		{ label: "CGenericNotificationToast", kind: CompletionItemKind.Class },
		{ label: "CheckButton", kind: CompletionItemKind.Class },
		{ label: "CIconPanel", kind: CompletionItemKind.Class },
		{ label: "CImageButton", kind: CompletionItemKind.Class },
		{ label: "CImagePanel", kind: CompletionItemKind.Class },
		{ label: "CImportFileDialog", kind: CompletionItemKind.Class },
		{ label: "CInputProxyPanel", kind: CompletionItemKind.Class },
		{ label: "CInWorldCurrencyStatus", kind: CompletionItemKind.Class },
		{ label: "CircularProgressBar", kind: CompletionItemKind.Class },
		{ label: "CItemMaterialCustomizationIconPanel", kind: CompletionItemKind.Class },
		{ label: "CItemModelPanel", kind: CompletionItemKind.Class },
		{ label: "CLabeledCommandComboBox", kind: CompletionItemKind.Class },
		{ label: "CLadderLobbyLeaderboard", kind: CompletionItemKind.Class },
		{ label: "CLoadGameDialog", kind: CompletionItemKind.Class },
		{ label: "CLoadoutParticleSlider", kind: CompletionItemKind.Class },
		{ label: "CLoadoutPresetPanel", kind: CompletionItemKind.Class },
		{ label: "CMainMenuNotificationsControl", kind: CompletionItemKind.Class },
		{ label: "CMatchMakingPanel", kind: CompletionItemKind.Class },
		{ label: "CMiniPvPRankPanel", kind: CompletionItemKind.Class },
		{ label: "CModelImagePanel", kind: CompletionItemKind.Class },
		{ label: "CModelPanel", kind: CompletionItemKind.Class },
		{ label: "CModePanel", kind: CompletionItemKind.Class },
		{ label: "CModeSelectionPanel", kind: CompletionItemKind.Class },
		{ label: "CMouseMessageForwardingPanel", kind: CompletionItemKind.Class },
		{ label: "CMutePlayerDialog", kind: CompletionItemKind.Class },
		{ label: "CMvMBombCarrierProgress", kind: CompletionItemKind.Class },
		{ label: "CMvMBossStatusPanel", kind: CompletionItemKind.Class },
		{ label: "CMVMCriteriaPanel", kind: CompletionItemKind.Class },
		{ label: "CMvMPlayerTicketStatusPanel", kind: CompletionItemKind.Class },
		{ label: "CMvMVictoryMannUpEntry", kind: CompletionItemKind.Class },
		{ label: "CMvMVictoryMannUpPanel", kind: CompletionItemKind.Class },
		{ label: "CMvMVictoryMannUpPlayerTab", kind: CompletionItemKind.Class },
		{ label: "CMvMVictoryPanelContainer", kind: CompletionItemKind.Class },
		{ label: "CMvMWaveLossPanel", kind: CompletionItemKind.Class },
		{ label: "CNavigationPanel", kind: CompletionItemKind.Class },
		{ label: "CNewGameDialog", kind: CompletionItemKind.Class },
		{ label: "CNotificationQueuePanel", kind: CompletionItemKind.Class },
		{ label: "CNotificationsPresentPanel", kind: CompletionItemKind.Class },
		{ label: "CNotificationToastControl", kind: CompletionItemKind.Class },
		{ label: "COfflinePractice_MapSelectionPanel", kind: CompletionItemKind.Class },
		{ label: "COfflinePractice_ModeSelectionPanel", kind: CompletionItemKind.Class },
		{ label: "COfflinePracticeServerPanel", kind: CompletionItemKind.Class },
		{ label: "ComboBox", kind: CompletionItemKind.Class },
		{ label: "ContinuousProgressBar", kind: CompletionItemKind.Class },
		{ label: "ControlNameCExLabel", kind: CompletionItemKind.Class },
		{ label: "ControlNameEditablePanel", kind: CompletionItemKind.Class },
		{ label: "ControlNameImagePanel", kind: CompletionItemKind.Class },
		{ label: "COptionsSubMultiplayer", kind: CompletionItemKind.Class },
		{ label: "CPanelListPanel", kind: CompletionItemKind.Class },
		{ label: "CPlayerListDialog", kind: CompletionItemKind.Class },
		{ label: "CPlayListEntry", kind: CompletionItemKind.Class },
		{ label: "CPreviewRotButton", kind: CompletionItemKind.Class },
		{ label: "CPublishedFileBrowserDialog", kind: CompletionItemKind.Class },
		{ label: "CPublishFileDialog", kind: CompletionItemKind.Class },
		{ label: "CPvPRankPanel", kind: CompletionItemKind.Class },
		{ label: "CQuestLogPanel", kind: CompletionItemKind.Class },
		{ label: "CQuestMapPanel", kind: CompletionItemKind.Class },
		{ label: "CQuestMapPathsPanel", kind: CompletionItemKind.Class },
		{ label: "CQuestStatusPanel", kind: CompletionItemKind.Class },
		{ label: "CQuickPlayBusyDialog", kind: CompletionItemKind.Class },
		{ label: "CQuickplayDialog", kind: CompletionItemKind.Class },
		{ label: "CReportPlayerDialog", kind: CompletionItemKind.Class },
		{ label: "CRGBAImagePanel", kind: CompletionItemKind.Class },
		{ label: "CRichTextWithScrollbarBorders", kind: CompletionItemKind.Class },
		{ label: "CScenarioInfoPanel", kind: CompletionItemKind.Class },
		{ label: "CSCHintIcon", kind: CompletionItemKind.Class },
		{ label: "CScrollableList", kind: CompletionItemKind.Class },
		{ label: "CScrollableQuestDetails", kind: CompletionItemKind.Class },
		{ label: "CScrollableQuestList", kind: CompletionItemKind.Class },
		{ label: "CSteamFriendsListPanel", kind: CompletionItemKind.Class },
		{ label: "CSteamWorkshopDialog", kind: CompletionItemKind.Class },
		{ label: "CSteamWorkshopItemPanel", kind: CompletionItemKind.Class },
		{ label: "CStoreItemControlsPanel", kind: CompletionItemKind.Class },
		{ label: "CStorePreviewClassIcon", kind: CompletionItemKind.Class },
		{ label: "CStorePreviewItemIcon", kind: CompletionItemKind.Class },
		{ label: "CStorePreviewItemPanel", kind: CompletionItemKind.Class },
		{ label: "CStorePricePanel", kind: CompletionItemKind.Class },
		{ label: "CTankProgressBar", kind: CompletionItemKind.Class },
		{ label: "CTeamMenu", kind: CompletionItemKind.Class },
		{ label: "CTFArrowPanel", kind: CompletionItemKind.Class },
		{ label: "CTFBadgePanel", kind: CompletionItemKind.Class },
		{ label: "CTFClassImage", kind: CompletionItemKind.Class },
		{ label: "CTFClassTipsItemPanel", kind: CompletionItemKind.Class },
		{ label: "CTFClassTipsPanel", kind: CompletionItemKind.Class },
		{ label: "CTFClientScoreBoardDialog", kind: CompletionItemKind.Class },
		{ label: "CTFFlagStatus", kind: CompletionItemKind.Class },
		{ label: "CTFFooter", kind: CompletionItemKind.Class },
		{ label: "CTFFreezePanel", kind: CompletionItemKind.Class },
		{ label: "CTFFreezePanelHealth", kind: CompletionItemKind.Class },
		{ label: "CTFHudEscort", kind: CompletionItemKind.Class },
		{ label: "CTFHudEscortProgressBar", kind: CompletionItemKind.Class },
		{ label: "CTFHudMannVsMachineScoreboard", kind: CompletionItemKind.Class },
		{ label: "CTFHudRobotDestruction_RobotIndicator", kind: CompletionItemKind.Class },
		{ label: "CTFHudRobotDestruction_StateImage", kind: CompletionItemKind.Class },
		{ label: "CTFHudTimeStatus", kind: CompletionItemKind.Class },
		{ label: "CTFImagePanel", kind: CompletionItemKind.Class },
		{ label: "CTFIntroMenu", kind: CompletionItemKind.Class },
		{ label: "CTFLayeredMapItemPanel", kind: CompletionItemKind.Class },
		{ label: "CTFLeaderboardPanel", kind: CompletionItemKind.Class },
		{ label: "CTFLocalPlayerBadgePanel", kind: CompletionItemKind.Class },
		{ label: "CTFLogoPanel", kind: CompletionItemKind.Class },
		{ label: "CTFMapStampsInfoDialog", kind: CompletionItemKind.Class },
		{ label: "CTFMatchMakingSearchStatusPanel", kind: CompletionItemKind.Class },
		{ label: "CTFMatchSummary", kind: CompletionItemKind.Class },
		{ label: "CTFParticlePanel", kind: CompletionItemKind.Class },
		{ label: "CTFPlayerModelPanel", kind: CompletionItemKind.Class },
		{ label: "CTFPlaylistPanel", kind: CompletionItemKind.Class },
		{ label: "CTFProgressBar", kind: CompletionItemKind.Class },
		{ label: "CTFStaticBadgePanel", kind: CompletionItemKind.Class },
		{ label: "CTFStreamPanel", kind: CompletionItemKind.Class },
		{ label: "CTFTeamButton", kind: CompletionItemKind.Class },
		{ label: "CTFTeamStatus", kind: CompletionItemKind.Class },
		{ label: "CTFTextWindow", kind: CompletionItemKind.Class },
		{ label: "CTFTrainingComplete", kind: CompletionItemKind.Class },
		{ label: "CTFVideoPanel", kind: CompletionItemKind.Class },
		{ label: "CTGAImagePanel", kind: CompletionItemKind.Class },
		{ label: "CTrainingDialog", kind: CompletionItemKind.Class },
		{ label: "CTrainingItemPanel", kind: CompletionItemKind.Class },
		{ label: "CustomTextureStencilGradientMapWidget", kind: CompletionItemKind.Class },
		{ label: "CvarToggleCheckButton", kind: CompletionItemKind.Class },
		{ label: "CVictoryPanel", kind: CompletionItemKind.Class },
		{ label: "CVictorySplash", kind: CompletionItemKind.Class },
		{ label: "CVoteSetupDialog", kind: CompletionItemKind.Class },
		{ label: "CWarLandingPanel", kind: CompletionItemKind.Class },
		{ label: "CWarningSwoop", kind: CompletionItemKind.Class },
		{ label: "CWarStandingPanel", kind: CompletionItemKind.Class },
		{ label: "CWaveCompleteSummaryPanel", kind: CompletionItemKind.Class },
		{ label: "CWaveStatusPanel", kind: CompletionItemKind.Class },
		{ label: "Divider", kind: CompletionItemKind.Class },
		{ label: "DuckLeaderboard", kind: CompletionItemKind.Class },
		{ label: "EditablePanel", kind: CompletionItemKind.Class },
		{ label: "FooterPanel", kind: CompletionItemKind.Class },
		{ label: "Frame", kind: CompletionItemKind.Class },
		{ label: "HTML", kind: CompletionItemKind.Class },
		{ label: "ImageButton", kind: CompletionItemKind.Class },
		{ label: "ImagePanel", kind: CompletionItemKind.Class },
		{ label: "Label", kind: CompletionItemKind.Class },
		{ label: "ListPanel", kind: CompletionItemKind.Class },
		{ label: "MaterialButton", kind: CompletionItemKind.Class },
		{ label: "MaterialImage", kind: CompletionItemKind.Class },
		{ label: "Menu", kind: CompletionItemKind.Class },
		{ label: "Panel", kind: CompletionItemKind.Class },
		{ label: "PanelListPanel", kind: CompletionItemKind.Class },
		{ label: "ProgressBar", kind: CompletionItemKind.Class },
		{ label: "RadioButton", kind: CompletionItemKind.Class },
		{ label: "RichText", kind: CompletionItemKind.Class },
		{ label: "RotatingProgressBar", kind: CompletionItemKind.Class },
		{ label: "RoundInfoOverlay", kind: CompletionItemKind.Class },
		{ label: "ScalableImagePanel", kind: CompletionItemKind.Class },
		{ label: "ScrollableEditablePanel", kind: CompletionItemKind.Class },
		{ label: "ScrollBar", kind: CompletionItemKind.Class },
		{ label: "SectionedListPanel", kind: CompletionItemKind.Class },
		{ label: "Slider", kind: CompletionItemKind.Class },
		{ label: "TextEntry", kind: CompletionItemKind.Class },
		{ label: "TFSectionedListPanel", kind: CompletionItemKind.Class },
		{ label: "VideoPanel", kind: CompletionItemKind.Class }
	],
	"autoresize": autoResizeValues,
	"pincorner": pinValues,
	"textalignment": [
		{ label: "center", kind: CompletionItemKind.Enum },
		{ label: "east", kind: CompletionItemKind.Enum },
		{ label: "north-east", kind: CompletionItemKind.Enum },
		{ label: "north-west", kind: CompletionItemKind.Enum },
		{ label: "north", kind: CompletionItemKind.Enum },
		{ label: "south-east", kind: CompletionItemKind.Enum },
		{ label: "south-west", kind: CompletionItemKind.Enum },
		{ label: "south", kind: CompletionItemKind.Enum },
		{ label: "west", kind: CompletionItemKind.Enum },
	],
	"paintbackgroundtype": [
		{ label: "0", kind: CompletionItemKind.Enum },
		{ label: "1", kind: CompletionItemKind.Enum },
		{ label: "2", kind: CompletionItemKind.Enum },
		{ label: "3", kind: CompletionItemKind.Enum },
	],
	"pin_corner_to_sibling": pinValues,
	"pin_to_sibling_corner": pinValues
}