export const waveSpawnKeys = [
	"ClosestPoint",
	"DoneOutput",
	"DoneWarningSound",
	"FirstSpawnOutput",
	"FirstSpawnWarningSound",
	"LastSpawnOutput",
	"LastSpawnWarningSound",
	"MaxActive",
	"Name",
	"RandomSpawn",
	"SpawnCount",
	"StartWaveOutput",
	"StartWaveWarningSound",
	"Support",
	"Template",
	"TotalCount",
	"TotalCurrency",
	"WaitBeforeStarting",
	"WaitBetweenSpawns",
	"WaitBetweenSpawnsAfterDeath",
	"WaitForAllDead",
	"WaitForAllSpawned",
	"Where"
].map((key) => key.toLowerCase())
